branch-defaults:
  default:
    environment: nestjs-env
  main:
    environment: devtalles
    group_suffix: null
environment-defaults:
  devtalles:
    branch: null
    repository: null
global:
  application_name: devtalles
  default_ec2_keyname: null
  default_platform: Node.js 22 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform: Node.js 18 running on 64bit Amazon Linux 2
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
