on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd backend && npm install --production
      - name: Install Prisma CLI
        run: cd backend && npm install prisma --save-dev
      - name: Run Prisma Migrate
        run: cd backend && npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Zip app
        run: cd backend && zip -r ../app.zip .

      - name: Deploy to Elastic Beanstalk
        run: pip install awsebcli && cd backend && eb init devtalles --region us-east-1 --platform "Node.js" && eb use nestjs-env && eb setenv DATABASE_URL=${{ secrets.DATABASE_URL }} JWT_SECRET=${{ secrets.JWT_SECRET }} PORT=${{ secrets.PORT }} && eb deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
